<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodumur@hryvinskyi.com>
 * @github: <https://github.com/scriptua>
 */

use Script\Base\Helpers\Html;

?>
<?php if ($quickshopGroup = $block->getGroupChildNames('quickview_tabs', 'getChildHtml')): ?>
    <?php $layout = $block->getLayout(); ?>
    <?php
    echo Html::beginTag('div', [
        'id' => 'script-quick-view-tabs',
        'class' => ['product', 'data', 'items'],
        'data' => [
            'mage-init' => [
                'tabs' => [
                    'openedState' => 'active',
                    'content' => '.qs-content',
                    'header' => '.qs-title',
                    'collapsibleElement' => '.qs-title'
                ]
            ]
        ]
    ]);
    ?>
        <?php foreach ($quickshopGroup as $name): ?>
            <?php
            $html = $layout->renderElement($name);
            if (!trim($html)) {
                continue;
            }
            $alias = $layout->getElementAlias($name);
            $contentId = $block->getChildData($alias, 'html_id');
            $contentClass = $block->getChildData($alias, 'html_class');
            $label = $block->getChildData($alias, 'title');
            ?>
            <div class="data item title qs-title" aria-labeledby="tab-label-<?php echo $contentId; ?>-title">
                <a class="data switch" tabindex="-1" data-role="trigger" href="#<?php echo $contentId; ?>" id="tab-label-<?php echo $contentId; ?>-title" data-toggle="switch">
                    <?php echo $label; ?>
                </a>
            </div>
            <div class="data item content qs-content <?php echo $contentClass ?>" id="<?php echo $contentId; ?>">
                <?php echo $html; ?>
            </div>
        <?php endforeach ?>
    </div>
<?php endif ?>
